---
- name: update packages
  apt:
    update_cache: yes

- name:  Install Packages
  apt: name=wget  update_cache=yes state=latest

- name: terraform install
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.12.2/terraform_0.12.2_linux_amd64.zip
    dest: /usr/bin
    remote_src: True
  tags:
    - terraform

