---
- name: import docker 
  tags: 'docker'
  include_tasks: docker.yml

- name: Remove useless apt packages from the cache
  tags: 'docker'
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  tags: 'docker'
  apt:
    autoremove: yes
